[pytest]
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20:kaggle_environments.*
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette.*
