"""Rule-based heuristic scorer -- the Week-0 MVP brain.

Two design rules were followed throughout, both aimed at Week 1 rather than at
squeezing the last Elo out of Week 0:

**No hardcoded card IDs.** Every judgement is derived from the engine's own card
data (types, HP, energy costs, weakness) or from the role tags that
``carddb.Role`` extracts from rules text. The scorer therefore pilots *any*
legal deck, which is what makes it usable as a sparring partner for the whole
league later, and what makes the H4 "simple deck vs combo deck" ablation a fair
test rather than a comparison of two differently-tuned bots.

**Everything tunable lives in :class:`HeuristicConfig`.** The genuinely
uncertain decisions -- whether to take the first turn, how eagerly to bench, how
much a knockout is worth relative to setup -- are named parameters with
documented defaults, not magic numbers buried in branches. Week 4's ablation
table is generated by sweeping this dataclass.

The scorer returns *scores*, not actions. The shell picks. That separation is
what lets the neural policy drop in later without touching selection, masking,
loop-guarding or budgeting.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Sequence

from ..core.actions import ActionCandidate
from ..core.carddb import Card, CardDB, Role
from ..core.clock import Deadline
from ..core.enums import (
    NEGATIVE_CONTEXTS,
    AreaType,
    CardType,
    EnergyType,
    OptionType,
    SelectContext,
    SelectType,
)
from ..core.obs import ObsView, PokemonView, damage_after_type, energy_shortfall
from .base import default_desired_count

__all__ = ["HeuristicPolicy", "HeuristicConfig"]


@dataclass
class HeuristicConfig:
    """Every judgement call the scorer makes, in one place."""

    # -- opening -----------------------------------------------------------
    #: Take the first turn when offered. In the 2026 Standard format the player
    #: going first cannot attack on turn 1 but does get a clean setup turn.
    #: For a low-variance evolution deck that trade is usually good; for pure
    #: aggro it is not. Unresolved by theory -> settled by ladder A/B
    #: (``tools/ab_first_turn.py``), which is why it is a flag.
    prefer_first: bool = True
    #: Redraw the opening hand only when it contains no Basic Pokemon.
    mulligan_only_without_basic: bool = True

    # -- board development -------------------------------------------------
    target_bench: int = 4
    bench_basic_bonus: float = 700.0
    #: A Basic that is the pre-evolution of something in our deck is worth far
    #: more on the bench than a dead-end Basic.
    evolution_base_bonus: float = 260.0
    #: Week 6: a candidate Pokemon shares a trainer-affiliation tag (e.g.
    #: "Team Rocket's") with a card already in play or hand whose own
    #: attack/ability cares about that tag's board count
    #: (``Role.BOARD_SCALING``/``Role.BOARD_GATED``). Deck-agnostic --
    #: derived from the card's own name and rules text, not hardcoded to any
    #: one archetype. Without this the scorer has no reason to build toward
    #: such a payoff at all, which measurably collapsed win rate for a real
    #: adopted deck this session (Week 5's ``rocket_heuristic`` bench).
    board_synergy_bonus: float = 320.0
    #: Week 8: benching an otherwise-unremarkable Basic late in the game,
    #: purely to thin it out of the remaining draw pile, when bench space is
    #: free and nothing else is competing for the slot.
    bench_thinning_bonus: float = 70.0
    #: Turn number after which bench-thinning kicks in -- too early and it
    #: competes with genuine board development for the same bonus.
    bench_thinning_min_turn: int = 8

    # -- main phase ordering ----------------------------------------------
    ability_base: float = 900.0
    evolve_base: float = 860.0
    play_base: float = 700.0
    attach_base: float = 620.0
    attack_base: float = 320.0
    #: Negative on purpose. Retreating burns the turn's tempo and discards the
    #: Energy paid for it, so it must be *justified* by one of the bonuses
    #: below rather than merely preferred over ending the turn.
    retreat_base: float = -150.0
    end_base: float = 0.0

    # -- combat ------------------------------------------------------------
    win_now: float = 1e6
    knockout_bonus: float = 4200.0
    prize_bonus: float = 600.0
    damage_weight: float = 0.9
    #: Attacking with a Pokemon whose own attack disables it next turn is a
    #: real cost when it does not trade for a prize.
    self_lock_penalty: float = 260.0
    #: The simulator meta contains hard walls that null all damage from ex
    #: attackers ("Mysterious Rock Inn"). Detected from text, not by card ID.
    wall_penalty: float = 2600.0

    #: Scales the damage-weighted "power progress" an attachment buys. Energy
    #: is the scarcest resource in the game, so this is the single most
    #: sensitive number in the file -- see ``_power_value``.
    attach_progress_weight: float = 6.0
    #: Concentrating Energy on one attacker beats spreading it. Large enough to
    #: dominate a marginal progress gain on a filler Pokemon.
    designated_attacker_bonus: float = 400.0
    #: Score for an attachment that buys nothing. Must be below ``end_base`` so
    #: that ending the turn is strictly preferred to wasting a card.
    overload_penalty: float = -400.0

    # -- resources ---------------------------------------------------------
    draw_when_hand_below: int = 5
    draw_bonus: float = 320.0
    #: Week 8: raised above ``draw_bonus``. "Deck thinning" -- searching your
    #: deck for a specific card -- is strictly better than a same-size raw
    #: draw when both are legal in the same decision, because search removes
    #: dead cards from future draws instead of just refunding hand size. The
    #: pre-Week-8 default (240, below draw_bonus's 320) had this backwards.
    search_bonus: float = 340.0
    gust_bonus: float = 500.0
    energy_accel_bonus: float = 260.0
    #: Never burn the once-per-turn Supporter on a marginal effect early.
    supporter_discount_when_full_hand: float = 260.0
    #: Week 8: a Judge/Iono-style "shuffle your hand into your deck"
    #: Supporter is sitting in hand. Anything else played or attached before
    #: it is spent for free -- it would otherwise just be shuffled away with
    #: no benefit to holding it.
    pre_shuffle_clear_bonus: float = 90.0

    # -- retreat -----------------------------------------------------------
    retreat_if_stuck_bonus: float = 900.0
    retreat_if_dying_bonus: float = 420.0
    retreat_hp_threshold: float = 0.34
    #: Retreat proactively to promote a stronger benched attacker, even when
    #: the Active could still attack. Plausible on paper; settled empirically
    #: by ``tools/ablate.py`` because retreating also discards Energy.
    retreat_to_swap_attacker: bool = False


class HeuristicPolicy:
    """Scores every legal option with hand-written Pokemon TCG reasoning."""

    name = "heuristic-v1"

    def __init__(
        self,
        deck_ids: Sequence[int],
        db: CardDB,
        config: HeuristicConfig | None = None,
    ) -> None:
        self._deck = list(deck_ids)
        self.db = db
        self.cfg = config or HeuristicConfig()

        # Precomputed once: which Basic names are evolution bases in this deck,
        # and which card is our primary attacker. Keeps the hot path allocation
        # free.
        names = {c.name for cid in self._deck if (c := db.card(cid))}
        self._evolution_bases = {
            c.evolves_from
            for cid in set(self._deck)
            if (c := db.card(cid)) and c.evolves_from and c.evolves_from in names
        }
        attackers = [
            c
            for cid in set(self._deck)
            if (c := db.card(cid)) and c.is_pokemon and c.attack_ids
        ]
        self._primary_attacker: Card | None = max(
            attackers,
            key=lambda c: max((a.damage for a in db.attacks_of(c.card_id)), default=0),
            default=None,
        )
        self._deck_energy_types = {
            c.energy_type
            for cid in set(self._deck)
            if (c := db.card(cid)) and c.is_basic_energy
        }
        # Week 8: total copies of each card name in the full 60-card deck,
        # used by the recovery-aware discard scorer to tell a redundant
        # discard from the last reachable copy of something important.
        self._deck_name_counts: dict[str, int] = Counter(
            c.name for cid in self._deck if (c := db.card(cid)) is not None
        )

    # -- Policy protocol ----------------------------------------------------

    def deck(self) -> list[int]:
        return list(self._deck)

    def desired_count(
        self,
        view: ObsView,
        candidates: Sequence[ActionCandidate],
        scores: Sequence[float],
    ) -> int:
        return default_desired_count(view, candidates, scores)

    def score(
        self,
        view: ObsView,
        candidates: Sequence[ActionCandidate],
        deadline: Deadline,
    ) -> list[float]:
        st = view.select_type
        ctx = view.context

        if st == SelectType.MAIN:
            return self._score_main(view, candidates)
        if st == SelectType.YES_NO:
            return self._score_yes_no(view, candidates)
        if st == SelectType.ATTACK:
            return [self._score_attack(view, c) for c in candidates]
        if st == SelectType.EVOLVE:
            return [self._score_evolve(view, c) for c in candidates]
        if st in (SelectType.ENERGY, SelectType.ATTACHED_CARD):
            return [self._score_energy_like(view, c) for c in candidates]
        if st == SelectType.COUNT:
            return self._score_count(view, candidates)
        if st == SelectType.SPECIAL_CONDITION:
            return [self._score_special_condition(c) for c in candidates]
        if st == SelectType.SKILL:
            # Ability activation order: keep the engine's order, which follows
            # the board layout and is the least surprising choice.
            return [float(len(candidates) - c.index) for c in candidates]

        # SelectType.CARD and CARD_OR_ATTACHED_CARD cover ~30 distinct contexts.
        return [self._score_card_context(view, c, ctx) for c in candidates]

    # ------------------------------------------------------------------
    # Main phase
    # ------------------------------------------------------------------

    def _score_main(self, view: ObsView, candidates: Sequence[ActionCandidate]) -> list[float]:
        cfg = self.cfg
        me, opp = view.me, view.opp
        bench_n = len(me.bench)
        hand_n = me.hand_count

        out: list[float] = []
        for c in candidates:
            t = c.option_type

            if t == OptionType.END:
                out.append(cfg.end_base)
            elif t == OptionType.ATTACK:
                out.append(self._score_attack(view, c))
            elif t == OptionType.ABILITY:
                out.append(self._score_ability(view, c, hand_n))
            elif t == OptionType.EVOLVE:
                out.append(cfg.evolve_base + self._score_evolve(view, c))
            elif t == OptionType.PLAY:
                out.append(self._score_play(view, c, bench_n, hand_n))
            elif t == OptionType.ATTACH:
                out.append(self._score_attach(view, c))
            elif t == OptionType.RETREAT:
                out.append(self._score_retreat(view))
            elif t == OptionType.DISCARD:
                out.append(self._score_discard(view, c))
            else:
                out.append(10.0)
        return out

    # -- attack ---------------------------------------------------------

    def _score_attack(self, view: ObsView, c: ActionCandidate) -> float:
        cfg = self.cfg
        atk = c.attack
        if atk is None:
            return cfg.attack_base

        my_active = view.me.active
        opp_active = view.opp.active

        if my_active is not None and energy_shortfall(my_active.energies, atk.energies) > 0:
            # Should not be offered, but never rank an unpayable attack.
            return -1e6

        if c.would_win_game:
            return cfg.win_now

        s = cfg.attack_base + cfg.damage_weight * c.est_damage
        if c.is_knockout:
            s += cfg.knockout_bonus + cfg.prize_bonus * c.ko_prizes
        else:
            if Role.SELF_LOCK in atk.roles:
                s -= cfg.self_lock_penalty
            if c.est_damage == 0 and not atk.text:
                s -= 120.0

        # Damage-prevention walls: "Prevent all damage ... by Pokemon ex".
        if my_active is not None and opp_active is not None:
            if self._is_walled(my_active, opp_active):
                s -= cfg.wall_penalty

        # Chip damage matters more when it sets up next turn's knockout.
        if opp_active is not None and not c.is_knockout and c.est_damage > 0:
            if c.est_damage * 2 >= opp_active.hp:
                s += 180.0
        return s

    def _is_walled(self, attacker: PokemonView, defender: PokemonView) -> bool:
        """Would the defender's own Ability zero our damage?

        Text-derived rather than ID-matched, so it also catches next month's
        reprint of the same effect.
        """
        acard, dcard = attacker.card, defender.card
        if acard is None or dcard is None or not dcard.has_ability:
            return False
        text = dcard.all_text.lower()
        if "prevent all damage" not in text:
            return False
        if "{ex}" in text or "pokémon ex" in text or "pokemon ex" in text:
            return acard.rule_box
        return True

    # -- ability --------------------------------------------------------

    def _score_ability(self, view: ObsView, c: ActionCandidate, hand_n: int) -> float:
        cfg = self.cfg
        s = cfg.ability_base
        card = c.card
        if card is None:
            return s
        roles = card.roles
        if Role.DRAW in roles and hand_n <= cfg.draw_when_hand_below:
            s += cfg.draw_bonus
        if Role.SEARCH in roles:
            s += cfg.search_bonus
        if Role.ENERGY_ACCEL in roles:
            s += cfg.energy_accel_bonus
            # Only worth it while we still hold energy to move.
            if view.me.basic_energy_in_hand == 0:
                s -= cfg.energy_accel_bonus + 150.0
        if Role.SELF_DISCARD_COST in roles and hand_n <= 2:
            s -= 400.0

        # Abilities paid for with Energy off their own Pokemon. Cheap when the
        # holder is an idle bench body, ruinous when it is the attacker we have
        # spent three turns powering up.
        if Role.SELF_ENERGY_COST in roles:
            holder = c.target
            s -= 150.0
            if holder is not None:
                designated = self._designated_attacker(view)
                before = self._power_value(holder, holder.energies)
                after = self._power_value(holder, list(holder.energies)[:-1])
                s -= cfg.attach_progress_weight * max(0.0, before - after)
                if designated is not None and holder.serial == designated.serial:
                    s -= cfg.designated_attacker_bonus
        return s

    # -- evolve ---------------------------------------------------------

    def _score_evolve(self, view: ObsView, c: ActionCandidate) -> float:
        """Value the HP and offence gained by evolving this specific target."""
        newc = c.card
        if newc is None:
            return 0.0
        target = c.target
        gain = 0.0
        if target is not None and target.card is not None:
            gain += (newc.hp - target.card.hp) * 0.35
            old_best = max((a.damage for a in self.db.attacks_of(target.card_id)), default=0)
            new_best = max((a.damage for a in self.db.attacks_of(newc.card_id)), default=0)
            gain += (new_best - old_best) * 0.30
            # Evolving the Active is usually more urgent than a bench body.
            if target.area == AreaType.ACTIVE:
                gain += 90.0
            # Evolving something already under pressure banks the HP.
            gain += target.damage_taken * 0.20
        else:
            gain += newc.hp * 0.20
        if newc.has_ability:
            gain += 120.0
        return gain

    # -- play from hand -------------------------------------------------

    def _score_play(
        self, view: ObsView, c: ActionCandidate, bench_n: int, hand_n: int
    ) -> float:
        cfg = self.cfg
        card = c.card
        if card is None:
            return cfg.play_base

        me, opp = view.me, view.opp

        if card.is_pokemon:
            if me.bench_open <= 0:
                return -200.0
            s = cfg.bench_basic_bonus
            if bench_n >= cfg.target_bench:
                s -= 260.0
            if card.name in self._evolution_bases:
                s += cfg.evolution_base_bonus
            # Do not volunteer extra prizes onto the bench.
            s -= 90.0 * (card.prizes_when_koed - 1)
            s += card.hp * 0.12
            s += self._board_synergy_bonus(view, card)
            s += self._bench_thinning_bonus(view, card)
            return s

        roles = card.roles
        s = cfg.play_base

        if card.is_supporter:
            if view.supporter_played:
                return -1e6  # engine should not offer it; never pick it
            if Role.DRAW in roles:
                s += cfg.draw_bonus if hand_n <= cfg.draw_when_hand_below else -cfg.supporter_discount_when_full_hand
            if Role.SEARCH in roles:
                s += cfg.search_bonus
            if Role.GUST in roles:
                s += self._gust_value(view)
            if Role.SELF_DISCARD_COST in roles and hand_n <= 2:
                s -= 400.0
            return s

        if card.card_type == CardType.STADIUM:
            if view.stadium_played:
                return -1e6
            return cfg.play_base - 250.0

        if card.card_type == CardType.TOOL:
            return cfg.play_base - 180.0

        # Items
        if Role.BALL in roles or Role.SEARCH in roles:
            s += cfg.search_bonus
            if me.pokemon_in_hand == 0:
                s += 180.0
        if Role.DRAW in roles and hand_n <= cfg.draw_when_hand_below:
            s += cfg.draw_bonus * 0.7
        if Role.GUST in roles:
            s += self._gust_value(view)
        if Role.SWITCH_SELF in roles and self._active_is_stuck(view):
            s += 420.0
        if Role.ENERGY_ACCEL in roles:
            s += cfg.energy_accel_bonus
        if Role.HEAL in roles:
            a = me.active
            s += 260.0 if (a is not None and a.hp_fraction < 0.5) else -300.0
        if Role.TURN_END in roles:
            s -= 900.0  # "Your turn ends." -- almost never right mid-turn
        if Role.SELF_DISCARD_COST in roles and hand_n <= 3:
            s -= 350.0
        if card.ace_spec:
            s += 120.0  # single copy: use it, but not before cheaper outs
        s += self._pre_shuffle_clearing_bonus(view)
        return s

    def _board_synergy_bonus(self, view: ObsView, card: Card) -> float:
        """General, deck-agnostic bonus for building board presence of a
        trainer-affiliation "tribe" (e.g. "Team Rocket's") when the team
        already has a card whose own attack/ability cares about that tag's
        board count (``Role.BOARD_SCALING``/``Role.BOARD_GATED``).

        Purely derived from ``Card.affiliation`` (name-parsed) and the
        text-pattern roles already tagged on every card/attack -- no card
        IDs, no archetype names, anywhere in this method. This is what lets
        the same scorer pilot a "go wide with your tribe" deck sensibly
        without ever having been written *for* that deck.
        """
        aff = card.affiliation
        if not aff:
            return 0.0

        me = view.me
        cares = False
        for pk in me.in_play():
            c = pk.card
            if c is not None and c.affiliation == aff and (Role.BOARD_SCALING in c.roles or Role.BOARD_GATED in c.roles):
                cares = True
                break
        if not cares:
            for c in me.hand_cards:
                if c is not None and c.affiliation == aff and (Role.BOARD_SCALING in c.roles or Role.BOARD_GATED in c.roles):
                    cares = True
                    break
        return self.cfg.board_synergy_bonus if cares else 0.0

    def _bench_thinning_bonus(self, view: ObsView, card: Card) -> float:
        """Late-game, benching an otherwise plain Basic purely to remove it
        from the remaining draw pile is worth a small bonus once bench space
        stops being a scarce resource for genuine board development."""
        cfg = self.cfg
        if view.turn < cfg.bench_thinning_min_turn:
            return 0.0
        if not card.basic or card.has_ability or card.name in self._evolution_bases:
            return 0.0
        return cfg.bench_thinning_bonus

    def _pre_shuffle_clearing_bonus(self, view: ObsView) -> float:
        """A Judge/Iono-style "shuffle your hand into your deck" Supporter
        (``Role.HAND_SHUFFLE``) is sitting in hand. Anything else played or
        attached before it is spent for free -- it would otherwise just get
        shuffled away with no benefit to holding it.

        Scoped to Supporters specifically (not any card whose text happens
        to match, e.g. an attack with the same wording) since the trigger
        this bonus reasons about is "still unplayed in my hand right now".
        """
        me = view.me
        for c in me.hand_cards:
            if c is not None and c.is_supporter and Role.HAND_SHUFFLE in c.roles:
                return self.cfg.pre_shuffle_clear_bonus
        return 0.0

    def _gust_value(self, view: ObsView) -> float:
        """How much is dragging up a benched Pokemon worth right now?"""
        me, opp = view.me, view.opp
        active = me.active
        if active is None or not opp.bench:
            return 0.0
        best = 0.0
        for b in opp.bench:
            dmg = active.best_damage_against(b)
            if dmg >= b.hp > 0:
                best = max(best, self.cfg.gust_bonus + 200.0 * b.prizes_given)
            elif b.card is not None and b.card.rule_box:
                best = max(best, 160.0)
        return best

    # -- attach ---------------------------------------------------------

    def _power_value(self, pk: PokemonView, energies: Sequence[int]) -> float:
        """How threatening is this Pokemon with this Energy attached?

        ``damage / (1 + 2 * shortfall)`` over its best attack. The shape matters
        more than the constants: it is *superlinear near completion*, so the
        last Energy that switches a 230-damage attack on is worth far more than
        the first, while a 30-damage attack that is already payable stays cheap.

        The naive alternative -- rank attachments by how much they reduce the
        energy shortfall -- looks reasonable and is badly wrong. It scores
        "switch on a 30-damage filler attack" identically to "advance the deck's
        actual win condition", so the agent sprays Energy across the bench and
        never powers its attacker. That was measured, not hypothesised: it cost
        roughly 25 points of win rate against a random opponent.
        """
        best = 0.0
        for atk in self.db.attacks_of(pk.card_id):
            short = energy_shortfall(energies, atk.energies)
            dmg = float(atk.damage) if atk.damage > 0 else 25.0
            best = max(best, dmg / (1.0 + 2.0 * short))
        return best

    def _designated_attacker(self, view: ObsView) -> PokemonView | None:
        """The one Pokemon we are trying to power up.

        Energy is the scarcest resource in the game (one manual attachment per
        turn plus whatever the deck accelerates), so concentrating it is almost
        always right. Prefer the Active unless something on the Bench is a
        materially bigger threat, in which case power that and let the retreat
        logic bring it forward.
        """
        me = view.me
        in_play = list(me.in_play())
        if not in_play:
            return None

        def ceiling(pk: PokemonView) -> float:
            return max((a.damage for a in self.db.attacks_of(pk.card_id)), default=0.0)

        best = max(in_play, key=lambda pk: (ceiling(pk), pk.n_energy))
        active = me.active
        if active is not None and ceiling(active) >= 0.6 * max(1.0, ceiling(best)):
            return active
        return best

    def _score_attach(self, view: ObsView, c: ActionCandidate) -> float:
        cfg = self.cfg
        target = c.target
        card = c.card
        if target is None:
            return cfg.attach_base

        s = cfg.attach_base
        provided = card.energy_type if (card and card.is_energy) else EnergyType.COLORLESS

        before = self._power_value(target, target.energies)
        after = self._power_value(target, list(target.energies) + [int(provided)])
        gain = after - before
        s += cfg.attach_progress_weight * max(0.0, gain)

        designated = self._designated_attacker(view)
        if designated is not None and target.serial == designated.serial:
            s += cfg.designated_attacker_bonus
        elif target.area == AreaType.ACTIVE:
            s += 150.0

        # Already fully powered and gaining nothing: this Energy is a dead
        # card. It must score *below* ending the turn, or the agent happily
        # buries seven Energy on a Pokemon that needed four.
        if gain <= 0.0 and self._min_shortfall(target, target.energies) == 0:
            return cfg.overload_penalty
        s += self._pre_shuffle_clearing_bonus(view)
        return s

    def _min_shortfall(self, pk: PokemonView, energies: Sequence[int]) -> int:
        best = 99
        for atk in self.db.attacks_of(pk.card_id):
            best = min(best, energy_shortfall(energies, atk.energies))
        return 0 if best == 99 else best

    # -- retreat --------------------------------------------------------

    def _better_attacker_on_bench(self, view: ObsView) -> bool:
        """Is there a benched Pokemon that would genuinely hit harder *now*?

        The earlier version asked only "can the Active attack, and can anything
        on the bench attack" -- which is true constantly, and produced retreats
        that swapped a powered attacker for an empty one and discarded the
        Energy paid for the retreat. Comparing realised damage against the
        current defender is the fix.
        """
        me, opp = view.me, view.opp
        a = me.active
        if a is None or not me.bench:
            return False
        target = opp.active
        current = a.best_damage_against(target) if target is not None else 0
        for b in me.bench:
            if self._min_shortfall(b, b.energies) != 0:
                continue
            dmg = b.best_damage_against(target) if target is not None else 0
            if target is not None and dmg >= target.hp > 0 and current < target.hp:
                return True  # the bench has lethal and the Active does not
            if dmg > current * 1.5 + 20:
                return True
        return False

    def _active_is_stuck(self, view: ObsView) -> bool:
        """Active cannot act at all, and something on the bench can."""
        me = view.me
        a = me.active
        if a is None:
            return False
        return self._min_shortfall(a, a.energies) > 0 and any(
            self._min_shortfall(b, b.energies) == 0 for b in me.bench
        )

    def _score_retreat(self, view: ObsView) -> float:
        cfg = self.cfg
        me, opp = view.me, view.opp
        a = me.active
        if a is None or view.retreated or not me.bench:
            return -1e6
        s = cfg.retreat_base

        # Would we simply be giving up a prize by staying?
        opp_active = opp.active
        if opp_active is not None and a.card is not None:
            incoming = opp_active.best_damage_against(a)
            if incoming >= a.hp > 0:
                s += cfg.retreat_if_dying_bonus * (1.0 + 0.5 * (a.prizes_given - 1))

        if self._active_is_stuck(view) and self._better_attacker_on_bench(view):
            s += cfg.retreat_if_stuck_bonus
        elif cfg.retreat_to_swap_attacker and self._better_attacker_on_bench(view):
            s += cfg.retreat_if_stuck_bonus * 0.45
        if a.hp_fraction < cfg.retreat_hp_threshold:
            s += 180.0
        # Retreating costs energy; that energy is usually better left attached.
        if a.card is not None:
            s -= 70.0 * a.card.retreat_cost
        return s

    # -- discard (Week 8: recovery-aware) --------------------------------

    def _copies_remaining_in_deck(self, view: ObsView, name: str) -> int:
        """How many copies of ``name`` are still un-accounted-for in the
        remaining deck pile: total copies in our 60-card deck minus every
        copy we can currently see in hand, discard, in play, or (when
        revealed) our own prizes.

        This double-counts a copy that has evolved into something else (the
        base stage's own name stops appearing in ``in_play()``), so it is an
        estimate, not exact tracking -- consistent with the rest of this
        file's stance that the shape of the incentive matters more than
        precision (see ``_power_value``'s docstring).
        """
        total = self._deck_name_counts.get(name, 0)
        if total == 0:
            return 0
        me = view.me
        seen = 0
        for c in me.hand_cards:
            if c is not None and c.name == name:
                seen += 1
        for d in me.discard:
            dc = self.db.card(d.get("id"))
            if dc is not None and dc.name == name:
                seen += 1
        for pk in me.in_play():
            if pk.card is not None and pk.card.name == name:
                seen += 1
        for p in me.prize:
            if p is not None:
                pc = self.db.card(p.get("id"))
                if pc is not None and pc.name == name:
                    seen += 1
        return max(0, total - seen)

    def _recovery_available(self, view: ObsView) -> bool:
        """A card that can fetch something back from the discard pile is
        currently in hand (``Role.RECOVERY``). Only checks hand, not the
        unseen remaining deck, since that is all we can actually know."""
        return any(
            c is not None and Role.RECOVERY in c.roles for c in view.me.hand_cards
        )

    def _score_discard(self, view: ObsView, c: ActionCandidate) -> float:
        """Week 8: "Track Your Recovery" -- a discard should cost more when
        it is the last reachable copy of something important than when it
        is a redundant duplicate or one we can fetch back.

        Replaces the pre-Week-8 flat ``-50.0`` penalty, which treated every
        discard identically regardless of recoverability.
        """
        card = c.card
        if card is None:
            return -50.0

        hand_dupes = sum(
            1 for x in view.me.hand_cards if x is not None and x.name == card.name
        ) - 1
        remaining_in_deck = self._copies_remaining_in_deck(view, card.name)
        if remaining_in_deck > 0 or hand_dupes > 0:
            return -25.0  # redundant: another reachable copy still exists

        if self._recovery_available(view):
            return -40.0  # last copy, but fetchable back from the discard

        # The last reachable copy, gone for good -- scale the cost with how
        # much this specific card is actually worth.
        return -50.0 - self._card_value(view, card)

    # ------------------------------------------------------------------
    # Yes / No
    # ------------------------------------------------------------------

    def _score_yes_no(self, view: ObsView, candidates: Sequence[ActionCandidate]) -> list[float]:
        cfg = self.cfg
        ctx = view.context
        yes = 1.0

        if ctx == SelectContext.IS_FIRST:
            yes = 1.0 if cfg.prefer_first else -1.0
        elif ctx == SelectContext.MULLIGAN:
            has_basic = any(
                c is not None and c.is_pokemon and c.basic for c in view.me.hand_cards
            )
            yes = -1.0 if (has_basic and cfg.mulligan_only_without_basic) else 1.0
        elif ctx == SelectContext.MORE_DEVOLVE:
            yes = -1.0
        elif ctx == SelectContext.COIN_HEAD:
            yes = 1.0  # fair coin: any fixed choice is optimal and deterministic
        elif ctx in (SelectContext.ACTIVATE, SelectContext.FIRST_EFFECT):
            card = view.context_card or view.effect_card
            yes = 1.0
            if card is not None:
                if Role.SELF_DISCARD_COST in card.roles and view.me.hand_count <= 2:
                    yes = -1.0
                if Role.TURN_END in card.roles:
                    yes = -1.0
        return [
            (yes if c.option_type == OptionType.YES else -yes) for c in candidates
        ]

    # ------------------------------------------------------------------
    # Numeric / condition selects
    # ------------------------------------------------------------------

    def _score_count(self, view: ObsView, candidates: Sequence[ActionCandidate]) -> list[float]:
        """Numeric choices: draw more, place more damage, remove more damage."""
        ctx = view.context
        prefer_high = ctx in (
            SelectContext.DRAW_COUNT,
            SelectContext.DAMAGE_COUNTER_COUNT,
            SelectContext.REMOVE_DAMAGE_COUNTER_COUNT,
        )
        out: list[float] = []
        for c in candidates:
            n = float(c.number if c.number is not None else c.index)
            if ctx == SelectContext.DRAW_COUNT and view.me.deck_count <= n + 1:
                # Decking out is an instant loss; never draw ourselves empty.
                out.append(-1e6)
                continue
            out.append(n if prefer_high else -n)
        return out

    def _score_special_condition(self, c: ActionCandidate) -> float:
        """Rank conditions by how much they actually cost us."""
        order = {
            0: 3.0,  # POISON  - recurring damage
            1: 3.5,  # BURN    - recurring damage plus a flip
            2: 5.0,  # SLEEP   - cannot attack or retreat
            3: 4.5,  # PARALYZE- cannot attack or retreat
            4: 2.0,  # CONFUSE - flip to attack
        }
        return order.get(int(c.special_condition or -1), 1.0)

    def _score_energy_like(self, view: ObsView, c: ActionCandidate) -> float:
        """Choosing among attached Energy / Tool cards.

        Contexts split cleanly into "pay a cost" (give up the cheapest thing)
        and "recover something" (take the most useful thing).
        """
        card = c.card
        value = 10.0
        if card is not None:
            value = 30.0 if card.card_type == CardType.SPECIAL_ENERGY else 12.0
            if card.energy_type in self._deck_energy_types:
                value += 6.0
        # Prefer taking energy off a Pokemon that is not our attacker.
        if c.target is not None and c.target.area == AreaType.ACTIVE:
            value += 10.0
        return -value if view.context in NEGATIVE_CONTEXTS else value

    # ------------------------------------------------------------------
    # Card selects (the long tail: ~30 contexts)
    # ------------------------------------------------------------------

    def _all_other_copies_prized(self, view: ObsView, name: str) -> bool:
        """True only when every copy of ``name`` *besides the one being
        valued* is confirmed sitting in our own prizes (revealed via
        ``view.me.prize``) -- i.e. we know for certain there is no backup
        copy left to draw or fetch this game.

        Prize contents are hidden by the game's own rules until taken, so
        this only ever fires on the rare occasions the engine's obs actually
        reveals one (e.g. after a card effect looks at prizes); it degrades
        to "no discount" otherwise, which is the safe default.
        """
        total = self._deck_name_counts.get(name, 0)
        if total <= 1:
            return False  # nothing "else" to be prized
        prized = sum(
            1
            for p in view.me.prize
            if p is not None
            and (pc := self.db.card(p.get("id"))) is not None
            and pc.name == name
        )
        return prized >= total - 1

    def _card_value(self, view: ObsView, card: Card | None) -> float:
        """Generic desirability of holding/keeping a card, in arbitrary units."""
        if card is None:
            return 8.0  # face-down: unknown, mildly interesting
        v = 20.0
        if card.is_pokemon:
            v = 40.0 + card.hp * 0.05
            if self._primary_attacker is not None and card.name == self._primary_attacker.name:
                v += 45.0
            if card.name in self._evolution_bases:
                v += 25.0
            if card.basic:
                v += 12.0
            if card.rule_box:
                v += 10.0
        elif card.is_basic_energy:
            v = 16.0
            if card.energy_type in self._deck_energy_types:
                v += 10.0
            if view.me.basic_energy_in_hand <= 1:
                v += 12.0
        elif card.card_type == CardType.SPECIAL_ENERGY:
            v = 30.0
        elif card.is_trainer:
            v = 24.0
            roles = card.roles
            if Role.DRAW in roles:
                v += 12.0
            if Role.BALL in roles or Role.SEARCH in roles:
                v += 14.0
            if Role.GUST in roles:
                # Week 8: prized-resource awareness -- don't overvalue this
                # copy's "there's always another one coming" assumption when
                # every backup copy is confirmed locked in our own prizes.
                v += 16.0 * (0.3 if self._all_other_copies_prized(view, card.name) else 1.0)
            if Role.RECOVERY in roles:
                v += 8.0
            if card.ace_spec:
                v += 20.0 * (0.3 if self._all_other_copies_prized(view, card.name) else 1.0)
        return v

    def _score_card_context(self, view: ObsView, c: ActionCandidate, ctx: int) -> float:
        cfg = self.cfg

        # --- setup: choosing the opening Active and Bench -----------------
        if ctx in (SelectContext.SETUP_ACTIVE_POKEMON, SelectContext.SETUP_BENCH_POKEMON):
            return self._score_setup(view, c, active=ctx == SelectContext.SETUP_ACTIVE_POKEMON)

        # --- promoting / switching ---------------------------------------
        if ctx in (SelectContext.SWITCH, SelectContext.TO_ACTIVE):
            return self._score_promote(view, c)

        # --- putting damage on the opponent ------------------------------
        if ctx in (
            SelectContext.DAMAGE_COUNTER,
            SelectContext.DAMAGE_COUNTER_ANY,
            SelectContext.DAMAGE,
        ):
            return self._score_damage_target(view, c)

        # --- healing / removing damage from ourselves --------------------
        if ctx in (SelectContext.HEAL, SelectContext.REMOVE_DAMAGE_COUNTER):
            t = c.target
            if t is None:
                return 0.0
            return t.damage_taken * 1.0 + (60.0 if t.area == AreaType.ACTIVE else 0.0)

        # --- attaching ----------------------------------------------------
        if ctx in (SelectContext.ATTACH_FROM, SelectContext.ATTACH_TO):
            return self._score_attach(view, c)

        # --- evolution targets -------------------------------------------
        if ctx in (SelectContext.EVOLVES_FROM, SelectContext.EVOLVES_TO):
            return self._score_evolve(view, c)

        # --- benching / putting into play --------------------------------
        if ctx in (SelectContext.TO_BENCH, SelectContext.TO_FIELD):
            card = c.card
            if card is None:
                return 0.0
            v = self._card_value(view, card)
            if card.name in self._evolution_bases:
                v += 30.0
            v -= 12.0 * (card.prizes_when_koed - 1)
            return v

        # --- generic value contexts --------------------------------------
        v = self._card_value(view, c.card)

        # Cards we are about to lose: prefer duplicates and dead weight.
        if ctx in NEGATIVE_CONTEXTS:
            if c.card is not None and c.card.is_basic_energy and view.me.basic_energy_in_hand > 4:
                v -= 10.0
            return -v
        return v

    # -- setup ----------------------------------------------------------

    def _score_setup(self, view: ObsView, c: ActionCandidate, active: bool) -> float:
        """Pick the opening board.

        The starter should be cheap to lose (single prize), able to survive a
        turn, and ideally the base of the line we actually want to evolve. The
        bench wants the opposite ordering only in that it happily accepts the
        big threats.
        """
        card = c.card
        if card is None or not card.is_pokemon:
            return -100.0
        v = card.hp * 0.10
        if card.name in self._evolution_bases:
            v += 60.0
        if card.attack_ids:
            cheapest = min(
                (len(a.energies) for a in self.db.attacks_of(card.card_id)), default=9
            )
            v += max(0.0, 30.0 - 8.0 * cheapest)
        if active:
            # Starting an ex in the Active spot donates prizes to an aggressive
            # opponent before we have a board.
            v -= 55.0 * (card.prizes_when_koed - 1)
            if card.retreat_cost >= 3:
                v -= 25.0
        else:
            v += 20.0 * (1 if card.rule_box else 0)
        return v

    def _score_promote(self, view: ObsView, c: ActionCandidate) -> float:
        """Which Pokemon should take the Active spot?"""
        t = c.target
        if t is None:
            card = c.card
            return self._card_value(view, card)
        opp_active = view.opp.active
        v = t.hp * 0.12
        if self._min_shortfall(t, t.energies) == 0:
            v += 220.0
            if opp_active is not None:
                dmg = t.best_damage_against(opp_active)
                v += dmg * 0.35
                if dmg >= opp_active.hp > 0:
                    v += 700.0
        # Do not promote something that dies immediately for extra prizes.
        if opp_active is not None:
            incoming = opp_active.best_damage_against(t)
            if incoming >= t.hp > 0:
                v -= 150.0 * t.prizes_given
        if t.card is not None:
            v -= 15.0 * t.card.retreat_cost
        return v
